kind: Service
apiVersion: v1
metadata:
 name: wildfly
spec:
   type: LoadBalancer
   selector:
     app: wildfly
   ports:
     - name: web
       protocol: TCP
       port: 8081
       targetPort: 8080
     - name: admin
       protocol: TCP
       port: 9991
       targetPort: 9990
